substitutions:
  customers:
    - pattern: "\\bGoldman Sachs\\b"
      replacement: "PrimeCustomer"
    - pattern: "\\bGoldman\\b"
      replacement: "PrimeCustomer"
    - pattern: "\\bGS\\b"
      replacement: "PrimeCustomer"
    - pattern: "\\bGoldman Sachs's\\b"
      replacement: "PrimeCustomer's"
    - pattern: "\\bGoldman's\\b"
      replacement: "PrimeCustomer's"
    - pattern: "\\bGS's\\b"
      replacement: "PrimeCustomer's"
    - pattern: "\\bJPMorgan Chase\\b"
      replacement: "EliteCustomer"
    - pattern: "\\bJPMorgan\\b"
      replacement: "EliteCustomer"
    - pattern: "\\bChase\\b"
      replacement: "EliteCustomer"
    - pattern: "\\bJPMorgan Chase's\\b"
      replacement: "EliteCustomer's"
    - pattern: "\\bJPMorgan's\\b"
      replacement: "EliteCustomer's"
    - pattern: "\\bChase's\\b"
      replacement: "EliteCustomer's"
    - pattern: "\\bBank of America\\b"
      replacement: "TopCustomer"
    - pattern: "\\bBofA\\b"
      replacement: "TopCustomer"
    - pattern: "\\bBoA\\b"
      replacement: "TopCustomer"
    - pattern: "\\bBank of America's\\b"
      replacement: "TopCustomer's"
    - pattern: "\\bBofA's\\b"
      replacement: "TopCustomer's"
    - pattern: "\\bBoA's\\b"
      replacement: "TopCustomer's"
  vendors:
    - pattern: "\\bHewlett Packard Enterprise\\b"
      replacement: "PrimeVendor"
    - pattern: "\\bHPE\\b"
      replacement: "PrimeVendor"
    - pattern: "\\bHewlett Packard Enterprise's\\b"
      replacement: "PrimeVendor's"
    - pattern: "\\bHPE's\\b"
      replacement: "PrimeVendor's"
    - pattern: "\\bLenovo\\b"
      replacement: "EliteVendor"
    - pattern: "\\bLenovo's\\b"
      replacement: "EliteVendor's"
    - pattern: "\\bSamsung\\b"
      replacement: "TopVendor"
    - pattern: "\\bSamsung's\\b"
      replacement: "TopVendor's"
    - pattern: "\\bSony\\b"
      replacement: "PreferredVendor"
    - pattern: "\\bSony's\\b"
      replacement: "PreferredVendor's"
  partners:
    - pattern: "\\bInfosys\\b"
      replacement: "PrimePartner"
    - pattern: "\\bInfosys's\\b"
      replacement: "PrimePartner's"
    - pattern: "\\bTata Consultancy Services\\b"
      replacement: "ElitePartner"
    - pattern: "\\bTCS\\b"
      replacement: "ElitePartner"
    - pattern: "\\bTata Consultancy Services's\\b"
      replacement: "ElitePartner's"
    - pattern: "\\bTCS's\\b"
      replacement: "ElitePartner's"
    - pattern: "\\bWipro\\b"
      replacement: "TopPartner"
    - pattern: "\\bWipro's\\b"
      replacement: "TopPartner's"
    - pattern: "\\bCognizant\\b"
      replacement: "PreferredPartner"
    - pattern: "\\bCognizant's\\b"
      replacement: "PreferredPartner's"